Layout/EmptyLineBetweenDefs:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundMethodBody:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false
