
# Unix
brew "ctags"
brew "git"
brew "openssl"
brew "reattach-to-user-namespace"
brew "the_silver_searcher"
brew "tmux"
brew "vim"
brew "fish"
brew "bash"
brew "bash-completion"
brew "ncdu"
brew "autojump"
brew "stow"
brew "aria2"
brew "pandoc"
brew "wget"
brew "excersism"

# Ruby
brew "chruby"
brew "ruby-install"

brew "python"

# Databases
brew "sqlite"
brew "postgres"
brew "mysql"
brew "redis"

# Heroku
brew "heroku-toolbelt"

cask "adobe-reader"
cask "java"
cask "iterm2"
cask "keepassx"
cask "sublime-text-dev"
cask "dropbox"
cask "flux"
cask "github-desktop"
cask "caffeine"
cask "caret"
cask "spotify"
cask "skype"
cask "vlc"
cask "slack"
cask "firefox"
cask "google-chrome"
cask "wkhtmltopdf"
cask "mactex"
cask "atom"


cask "ynab"
cask "adobe-photoshop-lightroom441"
cask "tunnelblick"

#mas "Evernote", id: 406056744
#mas "Xcode", id: 4497799835
